# Methods

## Data
The primary method on this page involves the collection of data related to:
- **CEO Gender**: Gathering information on whether the company's CEO is male or female.
- **Gender Equality Scores**: Quantitative metrics that assess the company's gender diversity, equity, and inclusion performance.
- **Financial Performance Metrics**: Key financial indicators, such as revenue, profit margins, and stock performance.

## Process
1. Get the **2023 Gender Assessment dataset** from https://www.worldbenchmarkingalliance.org/research/2023-gender-data-set/, and select companies located in North America from the total of 1,006 companies. (a CSV file)
2. Gather the **CEO Gender** information as original collection and add the data to the CSV file.
3. Get **CIK codes** of each selected company from SEC's CIK Lookup https://www.sec.gov/search-filings/cik-lookup.
4. Gather the **financial data** for each company by using their CIK codes to retrieve information from the SEC.gov API https://www.sec.gov/search-filings/edgar-application-programming-interfaces. (JSON files)
5. Clean and merge the collected data for analysis, ensuring consistency.
6. Extract all financial indicators, and manually select 10 important and useful financial indicators for subsequent analysis.
