---
title: "Progress log"
---

## To-do

* [x] Explore possible topics by brainstorming
* [x] Review related literature
* [x] Identify potential data sources
* [x] Utilize APIs to access and collect data
* [x] Apply data cleaning
* [x] Discuss the technical methods for conducting exploratory data analysis (EDA)
* [x] Assign unsupervised and supervised tasks
* [x] Construct and write the report
* [x] Deploy the project on the web


## Member-1: Jiayi Peng

[Click here to learn about Jiayi Peng](../Collaborators.qmd)

**Weekly project contribution log:**


**M: 11-4-2024** 

* [x] Coordinate with team member to set up weekly meeting time 

**M: 11-11-2024** 

* [x] Discuss and brainstorm the main themes during the first meeting 

**M: 11-18-2024** 

* [x] Identify and explore potential data sources relevant to the project

**W: 11-20-2024** 

* [x] Discuss which API to use for data crawling, and finally settled on the EDGAR API

**F: 11-22-2024** 

* [x] Discuss the strategy for merging datasets and performing initial data cleaning

**T: 11-28-2024** 

* [x] Discuss about which eda metrics to use

**W: 12-04-2024** 

* [x] Conduct text data cleaning

**T: 12-05-2024** 

* [x] Conduct text data eda

**S: 12-08-2024** 

* [x] Explore supervised learning analysis

**F: 12-13-2024** 

* [x] Discuss how to write our report


## Member-2: Kexin Lyu

[Click here to learn about Kexin Lyu](../Collaborators.qmd)

**Weekly project contribution log:**


**M: 11-4-2024** 

* [x] Coordinate with team member to set up weekly meeting time

**M: 11-11-2024** 

* [x] Discuss and brainstorm the main themes during the first meeting

**W: 11-20-2024** 

* [x] Discuss which API to use for data crawling, and finally settled on the EDGAR API

**F: 11-22-2024** 

* [x] Discuss the strategy for merging datasets and performing initial data cleaning

**T: 11-26-2024** 

* [x] Manually select which financial statement indicators to use based on accounting and finance knowledge

**T: 11-28-2024** 

* [x] Discuss about which eda metrics to use

**W: 12-04-2024** 

* [x] Conduct Univariate eda and Bivariate eda

**S: 12-08-2024** 

* [x] Explore unsupervised learning analysis

**F: 12-13-2024** 

* [x] Discuss how to write our report
